export const En = {
  light: 'Light',
  dark: 'Dark',
  selectLanguage: 'Select Language: ',
  en: 'EN',
  fa: 'FA',
  loading: 'Loading...',
  invalid: 'Invalid',
  logout: 'Logout',
  /** Login Scene */
  LoginSceneLogin: 'Login',
  LoginSceneEmail: 'Email',
  LoginScenePassword: 'Password',
  LoginSceneInputEmptyError: 'Please Enter Email & Password Correctly',
  LoginSceneWrongEmailFormat: 'Invalid Email',
  LoginSceneWrongPasswordFormat: 'Your Password must at least contain 8 characters',
  LoginSceneNewAccount: `Don't have an account?`,
  /** Register Scene */
  RegisterSceneRegister: 'Register',
  RegisterSceneName: 'Full Name',
  RegisterSceneEmail: 'Email',
  RegisterScenePassword: 'Password',
  RegisterSceneInputEmptyError: 'Please Enter Your Information Correctly',
  RegisterSceneWrongEmailFormat: 'Invalid Email',
  RegisterSceneWrongPasswordFormat: 'Your Password must at least contain 8 characters',
  RegisterSceneHaveAccount: `Already have an account?`,
  RegisterSceneNameError: 'Please Enter Your Name Correctly',
  /** SalesListScene */
  SalesListSceneTitle: 'Sales List',
  SalesListSceneAddSale: 'Add Sale',
  /** AddSaleScene */
  AddSaleSceneTitlePlaceholder: 'Sale Title',
  AddSaleScenePhoneNumberPlaceholder: '09905226632',
  AddSaleSceneAddressPlaceholder: 'North Avenue, St.Valiasr',
  AddSaleSceneDescriptionPlaceholder: 'Sale Description',
  AddSaleSceneTitle: 'Title',
  AddSaleScenePhoneNumber: 'Phone Number',
  AddSaleSceneAddress: 'Address',
  AddSaleSceneDescription: 'Description',
  AddSaleSceneAddSaleConfirm: 'Confirm',
  AddSaleScenePageTitle: 'Add Sale',
  AddSaleSceneAutoLocation: 'Auto Location Pick',
  AddSaleSceneYouAreHere: 'You Are Here',
  AddSaleScenePickLocationGuide: `Please Select Your Location\n(If Using Auto-Location Make sure not to have VPN on)`,
}
