export const En = {
  light: 'Light',
  dark: 'Dark',
  selectLanguage: 'Select Language: ',
  en: 'EN',
  fa: 'FA',
  /** Login Scene */
  LoginSceneLogin: 'Login',
  LoginSceneEmail: 'Email',
  LoginScenePassword: 'Password',
  LoginSceneInputEmptyError: 'Please Enter Email & Password Correctly',
  LoginSceneWrongEmailFormat: 'Invalid Email',
  LoginSceneWrongPasswordFormat: 'Your Password must at least contain 8 characters',
  LoginSceneNewAccount: `Don't have an account?`,
  /** Register Scene */
  RegisterSceneRegister: 'Register',
  RegisterSceneName: 'Full Name',
  RegisterSceneEmail: 'Email',
  RegisterScenePassword: 'Password',
  RegisterSceneInputEmptyError: 'Please Enter Your Information Correctly',
  RegisterSceneWrongEmailFormat: 'Invalid Email',
  RegisterSceneWrongPasswordFormat: 'Your Password must at least contain 8 characters',
  RegisterSceneHaveAccount: `Already have an account?`,
  RegisterSceneNameError: 'Please Enter Your Name Correctly',
}
