export const Fa = {
  light: 'روشن',
  dark: 'دارک',
  selectLanguage: 'زبان انتخابی: ',
  en: 'انگلیسی',
  fa: 'فارسی',
  /** Login Scene */
  LoginSceneLogin: 'ورود',
  LoginSceneEmail: 'ایمیل',
  LoginScenePassword: 'رمز عبور',
  LoginSceneInputEmptyError: 'لطفا ایمیل و رمز عبور خود را وارد کنید',
  LoginSceneWrongEmailFormat: 'ایمیل نامعتبر میباشد',
  LoginSceneWrongPasswordFormat: 'رمز عبور شما باید حداقل شامل 8 حرف باشد',
  LoginSceneNewAccount: 'حساب کاربری ندارید؟',
  /** Register Scene */
  RegisterSceneRegister: 'ثبت نام',
  RegisterSceneName: 'نام و نام خانوادگی',
  RegisterSceneEmail: 'ایمیل',
  RegisterScenePassword: 'رمز عبور',
  RegisterSceneInputEmptyError: 'لطفا اطلاعات خود را وارد کنید',
  RegisterSceneWrongEmailFormat: 'ایمیل نامعتبر میباشد',
  RegisterSceneWrongPasswordFormat: 'رمز عبور شما باید حداقل شامل 8 حرف باشد',
  RegisterSceneHaveAccount: 'حساب کاربری دارید؟',
  RegisterSceneNameError: 'لطفا نام خود را وارد کنید',
}
